import * as React from "react";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { axe } from "jest-axe";
import { describe, it, expect, vi } from "vitest";
import { Calendar } from "./calendar";

// ─── Helpers ──────────────────────────────────────────────────────────────────

// Use `defaultMonth` (uncontrolled) so clicking prev/next actually works.
// Passing `month` would lock the calendar to that month.
const APRIL_2026 = new Date(2026, 3, 1);

function renderCalendar(props?: React.ComponentProps<typeof Calendar>) {
  return render(<Calendar defaultMonth={APRIL_2026} {...props} />);
}

// Helper: find a day button by a day number, matching the aria-label that
// react-day-picker generates (format "PPPP" = e.g. "Wednesday, April 15th, 2026").
function getDayButton(dayNumber: number) {
  return screen.getAllByRole("button").find((btn) => {
    const label = btn.getAttribute("aria-label") ?? "";
    const text = btn.textContent ?? "";
    return text === String(dayNumber) || label.includes(`${dayNumber}`);
  });
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("Calendar", () => {
  describe("rendering", () => {
    it("renders the calendar grid", () => {
      renderCalendar();
      expect(screen.getByRole("grid")).toBeInTheDocument();
    });

    it("shows the current month and year label", () => {
      renderCalendar();
      expect(screen.getByText("April 2026")).toBeInTheDocument();
    });

    it("renders all 7 day-of-week headers", () => {
      renderCalendar();
      const headers = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"];
      for (const h of headers) {
        expect(screen.getByText(h)).toBeInTheDocument();
      }
    });

    it("renders previous and next month navigation buttons", () => {
      renderCalendar();
      expect(
        screen.getByRole("button", { name: /previous month/i })
      ).toBeInTheDocument();
      expect(
        screen.getByRole("button", { name: /next month/i })
      ).toBeInTheDocument();
    });

    it("has data-slot='calendar' on the root element", () => {
      const { container } = renderCalendar();
      expect(
        container.querySelector("[data-slot='calendar']")
      ).toBeInTheDocument();
    });

    it("renders outside-month days by default (showOutsideDays=true)", () => {
      renderCalendar();
      // March 29 / 30 / 31 appear before April 1 in the April grid.
      // react-day-picker marks them with data-outside.
      const { container } = render(<Calendar defaultMonth={APRIL_2026} />);
      const outsideDays = container.querySelectorAll("[data-outside='true']");
      expect(outsideDays.length).toBeGreaterThan(0);
    });
  });

  describe("month navigation", () => {
    it("navigates to the next month when the next button is clicked", async () => {
      const user = userEvent.setup();
      renderCalendar();

      expect(screen.getByText("April 2026")).toBeInTheDocument();
      await user.click(screen.getByRole("button", { name: /next month/i }));
      expect(screen.getByText("May 2026")).toBeInTheDocument();
    });

    it("navigates to the previous month when the previous button is clicked", async () => {
      const user = userEvent.setup();
      renderCalendar();

      expect(screen.getByText("April 2026")).toBeInTheDocument();
      await user.click(screen.getByRole("button", { name: /previous month/i }));
      expect(screen.getByText("March 2026")).toBeInTheDocument();
    });
  });

  describe("date selection", () => {
    it("calls onSelect with the chosen Date when a day is clicked", async () => {
      const user = userEvent.setup();
      const onSelect = vi.fn();
      renderCalendar({ mode: "single", onSelect });

      // Day button aria-labels are generated by labelDayButton (format "PPPP")
      // so we find the button for the 15th by its aria-label substring.
      const day15 = getDayButton(15);
      expect(day15).toBeInTheDocument();
      await user.click(day15!);

      expect(onSelect).toHaveBeenCalledTimes(1);
      const selected: Date = onSelect.mock.calls[0][0];
      expect(selected.getDate()).toBe(15);
      expect(selected.getMonth()).toBe(3); // April = 3
      expect(selected.getFullYear()).toBe(2026);
    });

    it("reflects a controlled selected date with aria-selected on the cell", () => {
      const selected = new Date(2026, 3, 15); // April 15
      const { container } = renderCalendar({ mode: "single", selected });

      // react-day-picker marks the selected <td> with aria-selected="true"
      const selectedCell = container.querySelector("[aria-selected='true']");
      expect(selectedCell).toBeInTheDocument();
    });
  });

  describe("disabled days", () => {
    it("applies disabled styles to a day matched by disabledDays", () => {
      const APRIL_15 = new Date(2026, 3, 15);
      const { container } = renderCalendar({
        mode: "single",
        disabled: APRIL_15,
      });

      // Query directly for a day button carrying the disabled classes we apply
      // in the DayButton override (opacity-30 cursor-not-allowed pointer-events-none).
      const disabledBtn = container.querySelector("button.opacity-30");
      expect(disabledBtn).toBeInTheDocument();
      expect(disabledBtn).toHaveClass("cursor-not-allowed");
      expect(disabledBtn).toHaveClass("pointer-events-none");
    });
  });

  describe("className merging", () => {
    it("appends custom className to the root element", () => {
      const { container } = renderCalendar({ className: "my-custom-class" });
      expect(container.querySelector("[data-slot='calendar']")).toHaveClass(
        "my-custom-class"
      );
    });
  });

  describe("accessibility", () => {
    it("has no axe violations", async () => {
      const { container } = renderCalendar({ mode: "single" });
      const results = await axe(container);
      expect(results).toHaveNoViolations();
    });
  });
});
